In [11]:
import pandas as pd
import os

In [12]:
cwd = os.getcwd()
parent_of_cwd = os.path.dirname(cwd)
log = pd.read_csv(f"{parent_of_cwd}/artifacts/shadow_log.csv")
slot_log = pd.read_csv(f"{parent_of_cwd}/artifacts/shadow_slot_log.csv")

In [13]:
slot_log['inference_run_at'].unique()

array(['2026-02-24 13:01:49', '2026-02-24 21:44:14',
       '2026-02-25 11:35:57', '2026-02-25 23:27:22'], dtype=object)

In [14]:
log.head()

,inference_run_id,invoice_id,customer_id,inference_run_at,model_version_id,current_attempt_no,snapshot_hour,days_into_dunning,suggested_optimal_retry_at,suggested_max_prob,raw_features_snapshot
0,0150f11f-258c-4cfc-ae4e-17e08833e362,1218660,e7745167-6032-4c0d-af05-75018291edde,2026-02-24 13:01:49,catboost_dunning_calibrated_20260224,8,13,5.0009,NaN,NaN,"{""status"": ""EXPIRED_DUNNING"", ""hours_since_bas..."
1,0150f11f-258c-4cfc-ae4e-17e08833e362,1224201,b8f2146f-53c8-418c-8642-d9620d141ac9,2026-02-24 13:01:49,catboost_dunning_calibrated_20260224,5,13,5.0009,NaN,NaN,"{""status"": ""EXPIRED_DUNNING"", ""hours_since_bas..."
2,0150f11f-258c-4cfc-ae4e-17e08833e362,1225239,b97dc171-701b-407b-8d11-5e6fd76b62b1,2026-02-24 13:01:49,catboost_dunning_calibrated_20260224,6,13,5.0006,NaN,NaN,"{""status"": ""EXPIRED_DUNNING"", ""hours_since_bas..."
3,0150f11f-258c-4cfc-ae4e-17e08833e362,1190717,e6ae2aea-a74e-4184-a9ef-506cedda7d97,2026-02-24 13:01:49,catboost_dunning_calibrated_20260224,11,13,5.0003,NaN,NaN,"{""status"": ""EXPIRED_DUNNING"", ""hours_since_bas..."
4,0150f11f-258c-4cfc-ae4e-17e08833e362,1234306,225e9466-f947-4c1a-b61e-ea5f657c343a,2026-02-24 13:01:49,catboost_dunning_calibrated_20260224,6,13,5.0000,2026-02-25 17:00:00,0.012795,"{""prev_decline_code"": ""UNKNOWN"", ""hour_sin"": -..."

## Comparison results

In [19]:
df_comparison = pd.read_csv(f"{parent_of_cwd}/artifacts/shadow_vs_actual_comparison.csv")

In [20]:
df_comparison

,inference_run_id,invoice_id,customer_id,inference_run_at,model_version_id,current_attempt_no,snapshot_hour,days_into_dunning,suggested_optimal_retry_at,suggested_max_prob,raw_features_snapshot,recovered,recovered_at,last_attempt_at,high_prob_missed_by_chargebee,hours_suggested_to_recovered,prob_bucket,recovered_within_top1_window
0,0150f11f-258c-4cfc-ae4e-17e08833e362,1218660,e7745167-6032-4c0d-af05-75018291edde,2026-02-24 13:01:49,catboost_dunning_calibrated_20260224,8,13,5.0009,NaN,NaN,"{""status"": ""EXPIRED_DUNNING"", ""hours_since_bas...",0,NaN,2026-02-19 13:00:34,False,NaN,NaN,False
1,0150f11f-258c-4cfc-ae4e-17e08833e362,1234351,d609a4a0-c778-4250-9de0-5c2365f27ec6,2026-02-24 13:01:49,catboost_dunning_calibrated_20260224,4,13,0.4200,2026-02-25 17:00:00,0.400000,"{""prev_decline_code"": ""UNKNOWN"", ""hour_sin"": -...",1,2026-02-24 14:13:27,2026-02-24 14:13:27,False,-26.775833,0.40,False
2,0150f11f-258c-4cfc-ae4e-17e08833e362,1252130,5db7d316-3167-44b9-b655-e965e0e49353,2026-02-24 13:01:49,catboost_dunning_calibrated_20260224,1,13,0.8414,2026-02-25 17:00:00,0.600000,"{""prev_decline_code"": ""UNKNOWN"", ""hour_sin"": -...",1,2026-02-24 16:50:15,2026-02-24 16:50:15,False,-24.162500,0.60,False
3,0150f11f-258c-4cfc-ae4e-17e08833e362,1252209,7ddb0ec9-5dc4-4201-a7af-671892ff877f,2026-02-24 13:01:49,catboost_dunning_calibrated_20260224,5,13,0.6736,2026-02-25 17:00:00,0.183007,"{""prev_decline_code"": ""UNKNOWN"", ""hour_sin"": -...",1,2026-02-24 18:50:55,2026-02-24 18:50:55,False,-22.151389,0.18,False
4,0150f11f-258c-4cfc-ae4e-17e08833e362,1245968,6f2262cd-5e6a-4f22-909b-ad77036a2ac3,2026-02-24 13:01:49,catboost_dunning_calibrated_20260224,1,13,4.8331,2026-02-25 17:00:00,0.098522,"{""prev_decline_code"": ""UNKNOWN"", ""hour_sin"": -...",0,NaN,2026-02-19 17:02:05,False,NaN,0.10,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22356,09bb07aa-e341-4a21-938f-27a3523523b5,1256134,ad2d6c93-5ba5-43a5-849e-499ce02070a6,2026-03-01 22:31:01,catboost_dunning_calibrated_20260224,2,22,2.7497,2026-03-03 03:00:00,0.500000,"{""prev_decline_code"": ""UNKNOWN"", ""hour_sin"": 0...",0,NaN,2026-02-27 04:31:25,True,NaN,0.50,False
22357,09bb07aa-e341-4a21-938f-27a3523523b5,1256135,d1954ee8-8a8f-4dfb-bf6f-8423c713d68d,2026-03-01 22:31:01,catboost_dunning_calibrated_20260224,1,22,2.7493,2026-03-03 03:00:00,0.421053,"{""prev_decline_code"": ""UNKNOWN"", ""hour_sin"": 0...",0,NaN,2026-02-27 04:31:58,True,NaN,0.42,False
22358,09bb07aa-e341-4a21-938f-27a3523523b5,1198502,fc94ca73-88e5-4de1-aa47-d25dde9003af,2026-03-01 22:31:01,catboost_dunning_calibrated_20260224,11,22,2.7487,2026-03-04 15:00:00,0.005367,"{""prev_decline_code"": ""UNKNOWN"", ""hour_sin"": -...",0,NaN,2026-02-27 04:32:50,False,NaN,0.01,False
22359,09bb07aa-e341-4a21-938f-27a3523523b5,1229820,ad4a93d4-626c-4955-8600-8d782efc5701,2026-03-01 22:31:01,catboost_dunning_calibrated_20260224,6,22,2.7599,2026-03-05 15:00:00,0.012539,"{""prev_decline_code"": ""UNKNOWN"", ""hour_sin"": -...",0,NaN,2026-02-27 04:16:43,False,NaN,0.01,False
22360,09bb07aa-e341-4a21-938f-27a3523523b5,1238521,168baa2a-d8b0-4e58-b90f-575aabbba181,2026-03-01 22:31:01,catboost_dunning_calibrated_20260224,5,22,0.0524,2026-03-05 19:00:00,0.013135,"{""prev_decline_code"": ""UNKNOWN"", ""hour_sin"": -...",0,NaN,2026-03-01 21:15:37,False,NaN,0.01,False